name: Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      # Secrets disponibles pendant les tests (optionnel selon ton code)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # AJOUTE ICI d'autres secrets si nécessaires (ex: JWT_SECRET)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  e2e-tests:
    name: E2E tests (Playwright)
    needs: unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: test
      # Secrets si tes E2E en ont besoin
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Installe Chromium + dépendances système pour Playwright
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run E2E tests (headless)
        run: npm run test:e2e